#1. Import the numpy package under the name

In [2]:
import numpy as np

 #2. Print the numpy version and the configuration

In [4]:
print np.version.version

1.11.0


#3. Create a null vector of size 10 

In [11]:
x = [] * 10
x_ray = np.asarray(x)
x_ray

array([], dtype=float64)

#4. How to find the memory size of any array

In [12]:
x_ray.nbytes

0

#7. Create a vector with values ranging from 10 to 49

In [16]:
seven = np.arange(10,49,5)
seven

array([10, 15, 20, 25, 30, 35, 40, 45])

#8. Reverse a vector (first element becomes last)

In [17]:
neves = seven[::-1]
neves

array([45, 40, 35, 30, 25, 20, 15, 10])

#9. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
threes = np.arange(0,9)
threes = threes.reshape(3,3)
threes


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#10. Find indices of non-zero elements from [1,2,0,0,4,0] 
Its kind of what is wanted, i guess the 0 position is ommitted because the array is 1 dimensional.

In [33]:
davy = [1,2,0,0,4,0]
david = np.asarray(davy)
for item in david:
    daniel = np.where (david != 0)
print daniel

(array([0, 1, 4]),)
