In [17]:
import numpy as np
a = np.arange(0,10)
b = np.ones(10)

In [18]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
np.add(a, b)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [21]:
np.subtract(a, b)

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [22]:
np.dot(a, b)

45.0

In [29]:
a = a.reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
a.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [31]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a[2,:]

array([4, 5])