In [3]:
import numpy as np
a = np.arange(0,10)
b = np.ones(7)
a
b
np.add(a,b)
np.subtract(a,b)
np.dot(a,b)
a.reshape(5,2)
a.ravel()
a.transpose()
a[2,0]

ValueError: operands could not be broadcast together with shapes (10,) (7,) 

In [5]:
import numpy as np
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a.reshape(11,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [9]:
a.transpose()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
b = np.arange(11,22)
b

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [13]:
np.add(a,b)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])

In [14]:
np.subtract(a,b)

array([-11, -11, -11, -11, -11, -11, -11, -11, -11, -11, -11])

In [15]:
import numpy as np

a = np.arange(50,150)
a.reshape(10,10)


990

In [16]:
a = np.arange(50,150)
print (a)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101 102 103
 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121
 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139
 140 141 142 143 144 145 146 147 148 149]


In [20]:
import numpy as np
import scipy
from scipy import stats
import random



a = np.arange(50,150)
for i in range(0,100):
    a[i] = random.randint(-1000,10000)
a = a.reshape(10,10)

def rows(x):
    largest_sum = 0
    largest_mean = 0
    largest_std = 0
    largest_sum_row = 0
    largest_mean_row = 0
    largest_std_row = 0
    for i in range(0,10):
        #Sum
        current_sum = x[i,0]+ x[i,1]+x[i,2]+ x[i,3]+x[i,4]+ x[i,5]+ x[i,6]+ x[i,7]+ x[i,8]+ x[i,9]
        #Mean
        current_mean = current_sum/10

        #Get the sum of the squares of the differences from the mean
        sum_of_squares = 0
        for z in range(0,10):
            sum_of_squares = (x[i,z]-current_mean)**2+sum_of_squares
        #Standard Deviation
        current_std = np.sqrt(sum_of_squares/10)
        if current_sum > largest_sum:
            largest_sum = current_sum
            larget_sum_row = i
        if current_mean > largest_mean:
            largest_mean = current_mean
            larget_mean_row = i
        if current_std > largest_std:
            largest_std = current_std
            larget_std_row = i
    print ("Largest Sum is", largest_sum,"on row", largest_sum_row)
    print ("Largest Mean is", largest_mean,"on row", largest_mean_row)
    print ("Largest Standard Deviation is", largest_std,"on row", largest_std_row)

def cols(x):
    largest_sum = 0
    largest_mean = 0
    largest_std = 0
    largest_sum_col = 0
    largest_mean_col = 0
    largest_std_col = 0
    for i in range(0,10):
        #Sum
        current_sum = x[0,i]+ x[1,i]+x[2,i]+ x[3,i]+x[4,i]+ x[5,i]+ x[6,i]+ x[7,i]+ x[8,i]+ x[9,i]
        #Mean
        current_mean = current_sum/10

        #Get the sum of the squares of the differences from the mean
        sum_of_squares = 0
        for z in range(0,10):
            sum_of_squares = (x[z,i]-current_mean)**2+sum_of_squares
        #Standard Deviation
        current_std = np.sqrt(sum_of_squares/10)
        if current_sum > largest_sum:
            largest_sum = current_sum
            larget_sum_col = i
        if current_mean > largest_mean:
            largest_mean = current_mean
            larget_mean_col = i
        if current_std > largest_std:
            largest_std = current_std
            larget_std_col = i
    print ("Largest Sum is", largest_sum,"on column", largest_sum_col)
    print ("Largest Mean is", largest_mean,"on column", largest_mean_col)
    print ("Largest Standard Deviation is", largest_std,"on column", largest_std_col)

rows(a)
cols(a)


('Largest Sum is', 69614, 'on row', 0)
('Largest Mean is', 6961, 'on row', 0)
('Largest Standard Deviation is', 3571.2972432996949, 'on row', 0)
('Largest Sum is', 71420, 'on column', 0)
('Largest Mean is', 7142, 'on column', 0)
('Largest Standard Deviation is', 3372.7127064130441, 'on column', 0)
