In [154]:
import numpy as np

#I could create a random column this way:
#b=np.random.randn(100)
#c = b.reshape(10,10)
#c

#but this one is better because I can see what the maximums should be:
b = np.arange(1,101)
c = b.reshape(10,10)
c

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [153]:
from itertools import chain

In [134]:
def funct(b):
    l = [0]*10 
    m = [0]*10 
    n = [0]*10 
    for i in range(1,11):
        ro = b[i-1:i,]         #select a row
        row = list(chain(*ro)) #changes array row to a list
        rowsum = np.sum(row)   #sums row-list
        l[i-1] = rowsum            #adds sum to empty list
        rowav = np.mean(row)   #averages row-list
        m[i-1] = rowav              #adds average to empty list
        rowstd = np.std(row)
        n[i-1] = rowstd
    print 'max sum: ' +str(max(l))
    print 'max avg: ' +str(max(m))
    print 'max std: ' +str(max(n))

funct(c)

max sum: 955
max avg: 95.5
max std: 2.87228132327


In [152]:
#for columns
def functc(b):
    o = [0]*10 
    p = [0]*10 
    q = [0]*10 
    for i in range(1,11):
        col = b[:,i-1]         #select a col
        colsum = np.sum(col)   #sums col-list
        o[i-1] = colsum            #adds sum to empty list
        colav = np.mean(col)   #averages col-list
        p[i-1] = colav              #adds average to empty list
        colstd = np.std(col)
        q[i-1] = colstd
    print 'max sum: ' +str(max(o))
    print 'max avg: ' +str(max(p))
    print 'max std: ' +str(max(q))

functc(c)

max sum: 550
max avg: 55.0
max std: 28.7228132327


In [160]:
#new matrix
d = np.ones(100)
e = d.reshape(10,10)
e

#sum:
f = c+e
print f

#difference
g = c-e
print g

#dot product
h = c*e
print h

[[   2.    3.    4.    5.    6.    7.    8.    9.   10.   11.]
 [  12.   13.   14.   15.   16.   17.   18.   19.   20.   21.]
 [  22.   23.   24.   25.   26.   27.   28.   29.   30.   31.]
 [  32.   33.   34.   35.   36.   37.   38.   39.   40.   41.]
 [  42.   43.   44.   45.   46.   47.   48.   49.   50.   51.]
 [  52.   53.   54.   55.   56.   57.   58.   59.   60.   61.]
 [  62.   63.   64.   65.   66.   67.   68.   69.   70.   71.]
 [  72.   73.   74.   75.   76.   77.   78.   79.   80.   81.]
 [  82.   83.   84.   85.   86.   87.   88.   89.   90.   91.]
 [  92.   93.   94.   95.   96.   97.   98.   99.  100.  101.]]
[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.